// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
	"seekF-backend/internal/controllers/user"
	"seekF-backend/internal/dao/user_dao"
	"seekF-backend/internal/router"
	"seekF-backend/internal/services/user_service"
)

// Injectors from wire.go:

// initApp 是 Wire 注入器函数
// Wire 会在编译期分析依赖关系，自动生成完整的初始化代码
func initApp(db *gorm.DB) App {
	userInfoDAO := userdao.NewUserInfoDAO(db)
	authService := userservice.NewAuthService(userInfoDAO)
	authController := user.NewAuthController(authService)
	userInfoService := userservice.NewUserInfoService(userInfoDAO)
	userInfoController := user.NewUserInfoController(userInfoService)
	groupDAO := userdao.NewGroupDAO(db)
	contactDAO := userdao.NewContactDAO(db)
	sessionDAO := userdao.NewSessionDAO(db)
	contactApplyDAO := userdao.NewContactApplyDAO(db)
	groupService := userservice.NewGroupService(groupDAO, contactDAO, sessionDAO, userInfoDAO, contactApplyDAO)
	groupController := user.NewGroupController(groupService)
	contactService := userservice.NewContactService(contactDAO, sessionDAO, userInfoDAO, groupDAO, contactApplyDAO)
	contactController := user.NewContactController(contactService)
	sessionService := userservice.NewSessionService(sessionDAO, userInfoDAO, groupDAO, contactDAO)
	sessionController := user.NewSessionController(sessionService)
	messageDAO := userdao.NewMessageDAO(db)
	messageService := userservice.NewMessageService(messageDAO, sessionDAO)
	messageController := user.NewMessageController(messageService)
	fileService := userservice.NewFileService()
	fileController := user.NewFileController(fileService)
	wsController := user.NewWsController()
	aiChatService := userservice.NewAIChatService(sessionDAO, messageDAO, userInfoDAO)
	aiChatController := user.NewAIChatController(aiChatService, fileService)
	knowledgeDAO := userdao.NewKnowledgeDAO(db)
	knowledgeService := userservice.NewKnowledgeService(knowledgeDAO)
	knowledgeController := user.NewKnowledgeController(knowledgeService)
	discoverDAO := userdao.NewDiscoverDAO(db)
	discoverService := userservice.NewDiscoverService(discoverDAO, userInfoDAO)
	discoverController := user.NewDiscoverController(discoverService)
	engine := router.SetupRouter(authController, userInfoController, groupController, contactController, sessionController, messageController, fileController, wsController, aiChatController, knowledgeController, discoverController)
	app := App{
		Router:         engine,
		SessionService: sessionService,
		MessageDAO:     messageDAO,
		SessionDAO:     sessionDAO,
		GroupDAO:       groupDAO,
		DiscoverDAO:    discoverDAO,
		UserInfoDAO:    userInfoDAO,
	}
	return app
}

// wire.go:

// DAO ProviderSet — 所有数据访问层依赖
var daoProviderSet = wire.NewSet(userdao.NewUserInfoDAO, userdao.NewContactDAO, userdao.NewSessionDAO, userdao.NewGroupDAO, userdao.NewContactApplyDAO, userdao.NewMessageDAO, userdao.NewKnowledgeDAO, userdao.NewDiscoverDAO)

// ServiceProviderSet — 所有业务逻辑层依赖
var serviceProviderSet = wire.NewSet(userservice.NewAuthService, userservice.NewUserInfoService, userservice.NewContactService, userservice.NewGroupService, userservice.NewSessionService, userservice.NewMessageService, userservice.NewFileService, userservice.NewAIChatService, userservice.NewKnowledgeService, userservice.NewDiscoverService)

// controllerProviderSet — 所有控制器依赖
var controllerProviderSet = wire.NewSet(user.NewAuthController, user.NewUserInfoController, user.NewContactController, user.NewGroupController, user.NewSessionController, user.NewMessageController, user.NewFileController, user.NewWsController, user.NewAIChatController, user.NewKnowledgeController, user.NewDiscoverController)

// App 包含所有需要暴露的依赖
// 全局单例（websocket、ai 等）需要通过 App 暴露给 main.go 使用
type App struct {
	Router         *gin.Engine
	SessionService userservice.SessionService
	MessageDAO     userdao.MessageDAO
	SessionDAO     userdao.SessionDAO
	GroupDAO       userdao.GroupDAO
	DiscoverDAO    userdao.DiscoverDAO
	UserInfoDAO    userdao.UserInfoDAO
}
